chat/urls.py
from django.urls import path

from chat.views import (
    chat_toko,
    chat_user,
    get_chatlist,
    get_messages,
    index,
    send_message,
    send_message_json
)

app_name = "chat"

urlpatterns = [
    path("messages/json/send", send_message_json),
    path("messages/send", send_message),
    path("messages/<int:cid>", get_messages),
    path("user/<int:uid>", chat_user),
    path("toko/<int:uid>", chat_toko),
    path("get", get_chatlist),
    path("", index),
]

landing/urls.py
from django.urls import path
from landing.views import show_landing, login_user, logout_user, register, login_flutter, logout_flutter, register_flutter

app_name = 'landing'

urlpatterns = [
    # TODO: Routing
    path('', show_landing, name='landing'),
    path('login/', login_user, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout_user, name='logout'),
    path('login_flutter/', login_flutter, name='login_flutter'),
    path('logout_flutter/', logout_flutter, name='logout_flutter'),
    path('register_flutter/', register_flutter, name='register_flutter'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("chat/", include("chat.urls")),
    # path("", include("helloworld.urls")),
    path("", include("landing.urls")),
    path("katalog/", include("katalog.urls")),
    path("detail/", include("detail.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("auth/", include("authentication.urls")),
]

landing/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Kontak(models.Model):
    pesan = models.TextField()

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    is_seller = models.BooleanField(default=False)

landing/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class SignUp(UserCreationForm):
    ROLES_CHOICES = [('S', 'Penjual'),
                     ('B', 'Pembeli'),]
    roles = forms.ChoiceField(
        label="Roles",
        required=True,
        choices=ROLES_CHOICES,
        widget=forms.RadioSelect() 
    )

    class Meta:
        model = User
        fields = ['username', 'roles', 'password1']

    def save(self, commit=True):
        user = super(SignUp, self).save(commit=False)
        user.roles = self.cleaned_data["roles"]

        if commit:
            user.save()

        return user

landing/views.py
from django.shortcuts import  render
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.forms.models import model_to_dict
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
import datetime
from django.contrib import messages
from django.shortcuts import redirect
from project_django.middleware import inject_toko
from .models import User, Profile
from django.http.response import JsonResponse
from django.views.decorators.csrf import csrf_exempt    
import json
from katalog.models import Toko

# Create your views here.

def show_landing(request):
    context = {}
    return render(request, "landing.html", context)

def register(request):
    if (request.method == "POST"):
        username = request.POST.get("username")
        email = request.POST.get("email")
        password = request.POST.get("password")
        repeat_password = request.POST.get("repeat_password")
        is_seller = False
        if (User.objects.filter(username=username) or User.objects.filter(email=email)):
            messages.info(request, "Username or email already taken!")
        elif (password == repeat_password):
            user = User.objects.create_user(username=username, email=email, password=password)
            user.save()
            if (request.POST.get("seller_choice") == "yes"):
                is_seller = True
            profile = Profile.objects.create(user=user, name=username, email=email, is_seller=is_seller)
            profile.save()
            print(profile.is_seller)
            print(profile.user)
            print(user.profile)
            return redirect("landing:login")
        else:
            messages.info(request, "Password and repeat password is different!")
    return render(request, "register.html")

@csrf_exempt
def register_flutter(request):
    data = json.loads(request.body)
    username = data['username']
    password = data['password']
    confirm_pass = data['confirm_password']
    print(username)
    print(password)
    print(confirm_pass)

    if (password == confirm_pass):
        try:
        #Cek jika username atau email sudah terdaftar
            user = User.objects.get(username=username)
            print(user)
            return JsonResponse({'status':'register gagal'})
        except (User.DoesNotExist):
        #Jika username belum terdaftar
            user = User.objects.create_user(username=username, password=password)
            return JsonResponse({'status':'register berhasil', 'username':username, 'password':password})

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("landing:landing")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

@csrf_exempt
def login_flutter(request):
    print("MASUK DISINI")
    data = json.loads(request.body)
    username = data['username']
    password = data['password']

    if request.method == 'POST':
        user = authenticate(username=username, password=password)
        temp = User.objects.get(username=username)
        try:
            toko = Toko.objects.get(pk=request.user.pk)
        except:
            toko = None
        print(temp.id)
        print("AUTENTHICATE")
        print(username)
        print(password)
        if user is not None:
            login(request, user)
            return JsonResponse({
                "status": True,
                "username": request.user.username,
                "id": temp.id,
                "message": "Successfully Logged In!",
                "user": model_to_dict(request.user),
                "toko": model_to_dict(toko) if toko else None,
            }, status=200)

        else:
             return JsonResponse({
                "status": False,
                "message": "Failed to Login!"
            }, status=401)
    else:
        return JsonResponse({
            "status": False,
            "message": "Failed to Login, your username/password may be wrong."
        }, status=401)

@csrf_exempt
def logout_flutter(request):
    logout(request)
    return JsonResponse({
            "status": True,
            "message": "Berhasil"
        }, status=200)


# Handling logout function
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('landing:login'))
    response.delete_cookie('last_login')
    return response

landing/templates/landing.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Jajan Yuk!</title>
    <link rel="stylesheet" href="{% static 'style/style.css' %}" />
  </head>

  <body>
    <div
      class="banner-image w-100 d-flex align-items-center position-relative"
      style="min-height: 100vh; background-color: #ffb942;">
      <img class="position-absolute" src="https://cdn-icons-png.flaticon.com/512/1390/1390737.png" alt="" style="right: 130px; width: 450px; height: 450px;">
      <div class="content text-left" style="z-index : 10; margin-left: 90px;">
        <h1 id="title">Delightful apps crafted with love</h1>
      </div>
    </div>

    <div class="container text-center col gap-5" style="width:100%;">
      <div class="mt-5">
        <br><br><br>

        <h1 class="features">
          <b>Features</b>
        </h1>

        <h5 style="color:rgba(142, 139, 139, 0.515);">Here are some of our features.</h5>
      </div>

      <div class=" row gap-5 mx-2 py-4">
        <div class="col border py-5 px-4" id="features">
          <i class="bi bi-grid" style="font-size: 3rem; left:0"></i>
          <h4 align="left">
            <b>KATALOG</b>
          </h4>
          <p align="left">Pada fitur ini akan ditampilkan semua toko yang sudah terdaftar pada database kami.</p>
        </div>
        <div class="col border py-5 px-4" id="features">
          <i class="bi bi-menu-button-wide-fill" style="font-size: 3rem;"></i>
          <h4 align="left">
            <b>DASHBOARD</b>
          </h4>
          <p align="left">Fitur ini akan dimiliki khusus bagi para penjual. Penjual dapat membuka toko, dan mengatur data yang akan ditampilkan. </p>
        </div>
        <div class="col border py-5 px-4" id="features">
          <i class="bi bi-chat-left-text" style="font-size: 3rem; left: 3px"></i>
          <h4 align="left">
            <b>CHAT</b>
          </h4>
          <p align="left">Pada fitur ini, pengguna dan penjual dapat berkomunikasi melalui halaman chatting.</p>
        </div>
        <div class="col border py-5 px-4" id="features">
          <i class="bi bi-search" style="font-size: 3rem;"></i>
          <h4 align="left">
            <b>DETAILS</b>
          </h4>
          <p align="left">Pada fitur ini, pengguna dapat melihat detail dari toko yang dipilih dan menampilkan barang yang dijual oleh toko.
            Pengguna juga dapat memberikan rating kepada toko.</p>
        </div>
      </div> 
    </div>

    <br><br><br><br><br><br><br><br>

    <script type="text/javascript">
      var nav = document.querySelector('nav');

      window.addEventListener('scroll', function () {
        if (window.pageYOffset > 100) {
          nav.classList.add('bg-dark', 'shadow');
        } else {
          nav.classList.remove('bg-dark', 'shadow');
        }
      });
    </script>
  </body>
</html>
{% endblock content %}

landing/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">
    <style>
        .gradient-custom {
            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            background-color: #ffb942;
        }
        body {
            overflow: hidden;
        }
    </style>

    <form method="POST" action="">
      {% csrf_token %}
      <section class="vh-100 gradient-custom">
          <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
              <div class="col-12 col-md-8 col-lg-6 col-xl-4">
                <div class="card bg-light text-dark" style="border-radius: 0rem;">
                  <div class="card-body p-5 text-center">
                    <div class="mb-md-5 mt-md-4 pb-5">
                      <h3 class="fw-bold mb-2 text-uppercase">SIGN IN</h3>
                      <p class="text-black-50 mb-3">Please enter your username and password!</p>
        
                      <div class="form-outline form-black mb-2">
                        <input type="text" name="username" placeholder="Username" class="form-control form-control-lg" />
                      </div>
        
                      <div class="form-outline form-black mb-4">
                        <input type="password" name="password" placeholder="Password" class="form-control form-control-lg" />
                      </div> 

                      <button class="btn btn-outline-dark btn-lg px-4" type="submit">Login</button>

                      <div class="d-flex justify-content-center text-center mt-4 pt-1"></div>
                      <div>
                        <p class="mb-0">Don't have an account? <a href="{% url 'landing:register' %}" class="text-blue-50 fw-bold">Sign Up</a></p>
                      </div>          
                    </div>          
                  </div>
                </div>
              </div>
            </div>
          </div>
      </section>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     


</div>

{% endblock content %}

landing/templates/register.html
{% extends 'base.html' %} 
{% load static %} 

{% block meta %}
<title>Register</title>
{% endblock meta %} 

{% block content %} 
  
<div class = "register">
  <style>
      .gradient-custom {
          /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
          background-color: #ffb942;
      }
      body {
          overflow: hidden;
      }
  </style>
            
<form method="POST" action="" id="register-form">
  {% csrf_token %}
  <section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-4">
          <div class="card bg-light text-dark" style="border-radius: 0rem;">
            <div class="card-body p-5 text-center">
              <div class="mb-md-5 mt-md-4 pb-5">
                <h3 class="fw-bold mb-2 text-uppercase">SIGN UP</h3>
                <p class="text-black-50 mb-3">Please enter your username and password!</p>

                <div class="form-outline form-black mb-2">
                  <input type="text" name="username" placeholder="Username" class="form-control form-control-lg" required/>
                </div>

                <div class="form-outline form-black mb-4">
                  <input type="text" name="email" placeholder="Email" class="form-control form-control-lg" required/>
                </div>

                <div class="form-outline form-black mb-6">
                  <input type="text" name="password" placeholder="Password" class="form-control form-control-lg" required/>
                </div>
                
                <div class="form-outline form-black mb-8">
                  <input type="text" name="repeat_password" placeholder="Repeat password" class="form-control form-control-lg" required/>
                </div>

                <div>
                  <br>
                  <h5>Are you a seller?</h5>
                  <input type="radio" id="yes" name="seller_choice" value="yes" required />
                  <label for="yes">Yes</label>
                  <input type="radio" id="no" name="seller_choice" value="no" required />
                  <label for="no">No</label>
                </div>
                <div>
                  <br>
                  <button class="btn btn-outline-dark btn-lg px-4" type="submit">Register</button>
                  <p>
                    Already have an account?
                    <b><a href="{% url 'landing:login' %}" class="link-info">
                      Login here
                    </a></b>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</form>
{% endblock content %}