chat/urls.py
from django.urls import path

from chat.views import (
    chat_toko,
    chat_user,
    get_chatlist,
    get_messages,
    index,
    send_message,
    send_message_json
)

app_name = "chat"

urlpatterns = [
    path("messages/json/send", send_message_json),
    path("messages/send", send_message),
    path("messages/<int:cid>", get_messages),
    path("user/<int:uid>", chat_user),
    path("toko/<int:uid>", chat_toko),
    path("get", get_chatlist),
    path("", index),
]

detail/urls.py
from django.urls import path
from detail.views import * 

app_name = "detail"

urlpatterns = [
    path('', detail_toko, name='detail_toko'),
    path('jam_json/', jam_json, name='jam_json'),
    path('barang_json/', barang_json, name='barang_json'),
    path('review/', review, name='review'),
    path('add_review/<int:id>', add_review, name='add_review'),
]

katalog/urls.py
from django.urls import path

from katalog.views import show_json, show_json_search, show_katalog, add_json_search_flutter, show_json_search_flutter

app_name = "katalog"

urlpatterns = [
    # TODO: Routing
    path("json_searched_flutter/", show_json_search_flutter, name="show_json_search_flutter"),
    path(
        "json_flutter/<str:nama_toko>/", add_json_search_flutter, name="show_json_search_flutter"
    ),
    path("", show_katalog, name="katalog"),  # sesuaikan dengan nama fungsi yang dibuat
    path("json/", show_json, name="json"),  # sesuaikan dengan nama fungsi yang dibuat
    path("json/<str:nama_toko>/", show_json_search, name="json"),  # sesuaikan dengan nama fungsi yang dibuat
]

project_django/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("chat/", include("chat.urls")),
    # path("", include("helloworld.urls")),
    path("", include("landing.urls")),
    path("katalog/", include("katalog.urls")),
    path("detail/", include("detail.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("auth/", include("authentication.urls")),
]

katalog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Toko(models.Model):
    class HargaToko(models.TextChoices):
        mahal = "mahal"
        sedang = "sedang"
        murah = "murah"

    class KondisiToko(models.TextChoices):
        ramai = "ramai"
        sedang = "sedang"
        sepi = "sepi"

    nama = models.CharField(max_length=128)
    kota = models.CharField(max_length=64)
    provinsi = models.CharField(max_length=64)
    lokasi = models.CharField(max_length=128)
    deskripsi = models.TextField()
    range_harga = models.CharField(max_length=6, choices=HargaToko.choices)
    buka = models.BooleanField(default=True)
    kondisi = models.CharField(max_length=6, choices=KondisiToko.choices)
    pemilik = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

class TokoUntukSearchFlutter(models.Model):
    class HargaToko(models.TextChoices):
        mahal = "mahal"
        sedang = "sedang"
        murah = "murah"

    class KondisiToko(models.TextChoices):
        ramai = "ramai"
        sedang = "sedang"
        sepi = "sepi"

    nama = models.CharField(max_length=128)
    kota = models.CharField(max_length=64)
    provinsi = models.CharField(max_length=64)
    lokasi = models.CharField(max_length=128)
    deskripsi = models.TextField()
    range_harga = models.CharField(max_length=6, choices=HargaToko.choices)
    buka = models.BooleanField(default=True)
    kondisi = models.CharField(max_length=6, choices=KondisiToko.choices)

katalog/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from katalog.models import *
from django.http.response import HttpResponse, HttpResponseNotFound
from django.http import HttpResponseRedirect
from django.core import serializers
import json
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
# @login_required(login_url="../login")
def show_katalog(request) :
    datakatalog = Toko.objects.all()
    context = {
        'datakatalog' : datakatalog
    }

    return render(request, 'katalog.html', context)

# @login_required(login_url="../login")
def show_json(request):
    datakatalog = Toko.objects.all()
    # datakatalog = Toko.objects.filter(pemilik=request.user)

    return HttpResponse(serializers.serialize('json', datakatalog))


def show_json_search(request, nama_toko):
    status = Toko.objects.filter(nama__icontains=nama_toko)
    return HttpResponse(serializers.serialize('json', status))

@csrf_exempt
def add_json_search_flutter(request, nama_toko):
    TokoUntukSearchFlutter.objects.all().delete()
    data = Toko.objects.filter(nama__icontains=nama_toko)
    for i in json.loads(serializers.serialize('json', data)):

        
        TokoUntukSearchFlutter(nama= i['fields']['nama'], kota= i['fields']['kota'], provinsi= i['fields']['provinsi'], lokasi= i['fields']['lokasi'], deskripsi= i['fields']['deskripsi'], range_harga= i['fields']['range_harga'], buka= i['fields']['buka'], kondisi= i['fields']['kondisi']).save()
    return HttpResponse(serializers.serialize('json', TokoUntukSearchFlutter.objects.all()))


def show_json_search_flutter(request):
    datakatalog = TokoUntukSearchFlutter.objects.all()
    
    return HttpResponse(serializers.serialize('json', datakatalog))

katalog/templates/katalog.html
{% extends 'base.html' %}
{% block content %}

<style>
    body {
        margin: 0px;
        padding: 0px;
        background: radial-gradient(#ffb942, #fded23);
    }
    
    .boxContainer{
        margin: auto;
        margin-top: 3%;
        position: relative;
        width: 300px;
        height: 50px;
        border: 5px solid #545454 ;
        padding: 0px 10px;
        border-radius: 50px;
    }
  
    footer {
        width: 100%;
        position:fixed;
        bottom:0;
    }

    .search-bar{
        height: 100%;
        width: 100%;
        vertical-align: middle;

    }

    .search {
        background: transparent;
        border: none;
        height: 50%;
        padding: 0px 5px;
        border-radius: 70px;
    }

    .btn btn-link{
        background: #ffb942!important;
        color: #fded23;    
    }

    .card {
        background: rgb(246, 233, 217);
        position: relative;
    }

    .card:hover{
        transform: scale(1.05);
        box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 10px 10px rgba(0,0,0,.06);
        background: #ffb942;
    }

    .row {
        margin-top: 10px;
        margin-bottom: 10px;
        margin-left: 70px;
        margin-right: 70px;
    }

    h2 {
        color: #ffb942;
    }

    a {
        background: #ffb942!important;
    }
    
    button {
        color: #545454!important;
    }
</style>

<div class="boxContainer" id="form-search">
    <form action="" name="myform" method="GET" class="search-bar">
        <label><input type="text" name="search" id="search" class="search" placeholder="Search Toko"></label>
        <button class="btn btn-link" id="search">Search</button>
    </form>
</div>
<hr>
<div class="row" id="rowId"></div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script>
    $(document).ready(function(){
        
  load_data();

  function load_data()
  {
            const queryString = window.location.search;
            const urlParams = new URLSearchParams(queryString);
            console.log(urlParams.get('search'));
            if (urlParams.get('search') == null) {
                $.ajax({
                    url:`/katalog/json/`,
                    type:"GET",
                    dataType: 'json',
                    success:function(response)
                    {
                        let data = ""
                        for (let i of response){
                            console.log(0)
                            data += `<div >
                                        <div class="card w-65">
                                            <div class="card text-center">
                                                <h2 class="card-header">${ i.fields.nama }</h2>
                                            </div>
                                                <div class="card-body">
                                                    <h5 class="card-text">${ i.fields.deskripsi }</h5>
                                                    <p class="card-text">${ i.fields.lokasi }, ${ i.fields.kota }, ${ i.fields.provinsi }</p>
                                                    <div class="card text-right">
                                                        <a href="{% url 'detail:detail_toko' %}" class="btn btn-warning">Details</a>                       
                                                    </div>
                                                    <hr>
                                                    <div class="box"><div class="box">Range harga: ${ i.fields.range_harga }</div>
                                                    <div class="box"><div class="box">Buka: ${ i.fields.buka }</div>
                                                    <div class="box"><div class="box">Kondisi: ${ i.fields.kondisi }</div>
                                                </div>  
                                                        <div class="card text-center">
                                                            <div class="card text-right">
                                                                <a href="{% url 'detail:review' %}" class="btn btn-warning">Review</a>                       
                                                            </div>
                                                        </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <br>`
                                        
                        }
    
                        $('#rowId').html(data);
                    }
                });
            } else {
                $.ajax({
                    url:`/katalog/json/${urlParams.get('search')}`,
                    type:"GET",
                    dataType: 'json',
                    success:function(response)
                    {
                        let data = ""
                        for (let i of response){
                            console.log(0)
                            data += `<div>
                                        <div class="card w-65">
                                            <div class="card text-center">
                                                <h2 class="card-header">${ i.fields.nama }</h2>
                                            </div>
                                                <div class="card-body">
                                                    <h5 class="card-text">${ i.fields.deskripsi }</h5>
                                                    <p class="card-text">${ i.fields.lokasi }, ${ i.fields.kota }, ${ i.fields.provinsi }</p>
                                                    <div class="card text-right">
                                                        <a href="{% url 'detail:detail_toko' %}" class="btn btn-warning">Details</a>                       
                                                    </div>
                                                    <hr>
                                                    <div class="box"><div class="box">Range harga: ${ i.fields.range_harga }</div>
                                                    <div class="box"><div class="box">Buka: ${ i.fields.buka }</div>
                                                    <div class="box"><div class="box">Kondisi: ${ i.fields.kondisi }</div>
                                                </div>  
                                                        <div class="card text-center">
                                                            <div class="card text-right">
                                                                <a href="{% url 'detail:review' %}" class="btn btn-warning">Review</a>                       
                                                            </div>
                                                        </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <br>`
                                        
                        }
                        $('#rowId').html(data);
                    }
                });
            }
   
   }

        $("#button").click(load_data);
 });
</script>

{% endblock content %}